Repository PKNU-JavaStudy/mozip_backend, pull requests merged in 2024-07, with the labels that each got.

#121 [#120]Feat: Mybatis 로그 설정
  build.gradle
  src/main/java/com/mozip/config/MyBatisConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/logback-spring.xml
Labels: enhancement

#124 자바 스크립트 파일생성 및 분리
  src/main/resources/static/js/01jaeyoung.js
  src/main/resources/static/js/04jisoo.js
  src/main/resources/static/js/find_id.js
  src/main/resources/static/js/login.js
  src/main/resources/static/js/mypage_edit.js
  src/main/resources/static/js/recruit_create.js
  src/main/resources/static/js/recruit_detail.js
  src/main/resources/static/js/recruit_edit.js
  src/main/resources/static/js/recruit_list.js
  src/main/resources/static/js/show_detail.js
  src/main/resources/static/js/show_edit.js
  src/main/resources/static/js/teamnote.js
  src/main/resources/templates/auth/find_id.html
  src/main/resources/templates/auth/login.html
  src/main/resources/templates/member/mypage_edit.html
  src/main/resources/templates/project/recruit_create.html
  src/main/resources/templates/project/recruit_detail.html
  src/main/resources/templates/project/recruit_edit.html
  src/main/resources/templates/project/recruit_list.html
  src/main/resources/templates/project/show_detail.html
  src/main/resources/templates/project/show_edit.html
  src/main/resources/templates/team/teamnote.html
Labels: enhancement

#126 Fix/project create
  src/main/java/com/mozip/config/WebConfig.java
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/dto/req/project/ShowEditDto.java
  src/main/java/com/mozip/dto/resp/project/ShowListDto.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/resources/application-dev.yml
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/static/css/list.css
  src/main/resources/static/js/recruit_detail.js
  src/main/resources/templates/auth/find_id.html
  src/main/resources/templates/auth/join.html
  src/main/resources/templates/auth/login.html
  src/main/resources/templates/member/mypage_edit.html
  src/main/resources/templates/project/recruit_create.html
  src/main/resources/templates/project/recruit_detail.html
  src/main/resources/templates/project/recruit_edit.html
  src/main/resources/templates/project/show_detail.html
  src/main/resources/templates/project/show_edit.html
  src/main/resources/templates/project/show_list.html
Labels: bug

#128 프로젝트 삭제 쿼리 및 로직 수정
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/resources/mappers/ProjectMapper.xml
Labels: enhancement

#130 Topic/search
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/web/api/ApiProjectController.java
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/static/css/list.css
  src/main/resources/templates/project/recruit_list.html
  src/main/resources/templates/project/show_list.html
Labels: enhancement

#134 프로젝트 자랑하기 구현(서버단)
  src/main/java/com/mozip/config/SecurityConfig.java
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/domain/teamnote/TeamnoteRepository.java
  src/main/java/com/mozip/service/MemberService.java
  src/main/java/com/mozip/service/TeamService.java
  src/main/java/com/mozip/web/MemberController.java
  src/main/java/com/mozip/web/TeamController.java
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/static/css/list.css
  src/main/resources/templates/member/myproject_list.html
  src/main/resources/templates/project/recruit_create.html
  src/main/resources/templates/project/show_list.html
  src/main/resources/templates/team/teamnote.html
Labels: enhancement

#136 [#135]Feat : 프로젝트 자랑 전 리스트 구현 및 채용공고 레이아웃 추가
  src/main/java/com/mozip/web/MemberController.java
  src/main/java/com/mozip/web/ProjectController.java
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/static/css/list.css
  src/main/resources/static/css/recruit.css
  src/main/resources/templates/fragment/header.html
  src/main/resources/templates/member/myproject_list.html
  src/main/resources/templates/project/recruit_job.html
Labels: enhancement

#138 사람인API 연동 세팅
  build.gradle
  src/main/java/com/mozip/config/SecurityConfig.java
  src/main/java/com/mozip/config/WebConfig.java
  src/main/java/com/mozip/web/ProjectController.java
  src/main/java/com/mozip/web/api/ApiProjectController.java
  src/main/resources/application-dev.yml
  src/main/resources/templates/fragment/header.html
  src/main/resources/templates/project/recruit_edit.html
  src/main/resources/templates/project/recruit_job.html
Labels: enhancement

#140 find_id, find_password, update_password 액션 타임리프 수정
  src/main/resources/templates/auth/find_id.html
  src/main/resources/templates/auth/find_password.html
  src/main/resources/templates/auth/update_password.html
Labels: enhancement

#142 [#137]Feat: 사람인 채용공고 API 연동
  src/main/java/com/mozip/config/ApplicationConfig.java
  src/main/java/com/mozip/config/SecurityConfig.java
  src/main/java/com/mozip/config/WebConfig.java
  src/main/java/com/mozip/web/api/ApiSaraminController.java
  src/main/resources/templates/project/recruit_job.html
Labels: enhancement

#144 [#143]Feat: 프로젝트 자랑 기술스택 갯수 제한, 프로젝트 자랑 상세페이지 ui 수정
  src/main/resources/static/js/show_list.js
  src/main/resources/templates/project/show_list.html
Labels: enhancement

#145 [#141]Feat: 에러 페이지 만들기
  src/main/java/com/mozip/config/SecurityConfig.java
  src/main/resources/static/img/400.png
  src/main/resources/static/img/404.png
  src/main/resources/static/img/500.png
  src/main/resources/static/img/xx.png
  src/main/resources/templates/error/400.html
  src/main/resources/templates/error/404.html
  src/main/resources/templates/error/4xx.html
  src/main/resources/templates/error/500.html
  src/main/resources/templates/error/5xx.html
Labels: enhancement

#147 [#146]Fix: 프로젝트 작성,수정글 제목,주제,소개 글자수 제한 및 기술스택 갯수 제한
  src/main/java/com/mozip/dto/req/project/ProjectCreateDto.java
  src/main/resources/static/css/create.css
  src/main/resources/static/js/dynamicSkills.js
  src/main/resources/static/js/recruit_create.js
  src/main/resources/static/js/recruit_edit.js
  src/main/resources/templates/project/recruit_create.html
  src/main/resources/templates/project/recruit_edit.html
Labels: enhancement

#149 [#148]Design: 프로젝트 자랑 css
  src/main/resources/static/js/show_list.js
  src/main/resources/templates/project/show_detail.html
Labels: bug

#152 [#151]Fix: 자랑 리스트에 게시물 클릭시 undefined 에러 수정
  src/main/resources/static/js/show_list.js
Labels: bug

#154 [#153]Feat : 프로젝트 모집 검색 로직 수정 및 css 수정
  src/main/java/com/mozip/MozipApplication.java
  src/main/resources/static/css/detail.css
  src/main/resources/static/js/show_list.js
  src/main/resources/templates/project/recruit_list.html
Labels: bug

#155 [#150]Fix: 프로젝트 참여신청 로직 변경
  src/main/java/com/mozip/config/MyBatisConfig.java
  src/main/java/com/mozip/domain/member/Member.java
  src/main/java/com/mozip/domain/member/Role.java
  src/main/java/com/mozip/handler/RoleTypeHandler.java
  src/main/resources/mappers/AuthMapper.xml
  src/main/resources/static/js/recruit_detail.js
  src/main/resources/templates/project/recruit_detail.html
Labels: bug

#157 [#156]Feat : 채용공고 api 렌더링 수정
  src/main/java/com/mozip/web/api/ApiSaraminController.java
  src/main/resources/static/css/recruit.css
  src/main/resources/templates/project/recruit_job.html
Labels: bug

#159 프로젝트 모집 리스트 쿼리 수정
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/templates/project/recruit_list.html
Labels: bug

#160 Fix/recruit update info
  src/main/java/com/mozip/service/MemberService.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/templates/project/show_edit.html
Labels: bug

#162 [#161] Feat: 공유하기 버튼 클릭시 현재 url 복사
  src/main/resources/static/js/recruit_detail.js
  src/main/resources/static/js/show_detail.js
  src/main/resources/templates/project/recruit_detail.html
  src/main/resources/templates/project/show_detail.html
Labels: enhancement

#167 [#165] Fix: 공유하기 버그 수정
  src/main/resources/static/js/recruit_detail.js
  src/main/resources/static/js/show_detail.js
Labels: bug

#164 [#163] Feat: 마이페이지 북마크 필터링
  src/main/resources/static/js/mypage.js
  src/main/resources/templates/member/mypage.html
Labels: bug, enhancement

#168 Fix: 회원탈퇴 로직 추가
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/service/MemberService.java
  src/main/resources/mappers/ProjectMapper.xml
Labels: bug

#170 Fix: 마이페이지 북마크 스타일 수정
  src/main/resources/static/css/mypage.css
  src/main/resources/static/js/mypage.js
  src/main/resources/templates/member/mypage.html
Labels: enhancement

#174 [#173]Feat: 프로젝트모집 무한스크롤 추가
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/web/api/ApiProjectController.java
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/static/js/recruit_list.js
  src/main/resources/templates/project/recruit_job.html
  src/main/resources/templates/project/recruit_list.html
Labels: enhancement

#178 리드미 수정2
  src/main/resources/static/gif/로그아웃.gif
  src/main/resources/static/gif/로그인.gif
Labels: bug

#179 프로젝트 자랑 목록 변경
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/static/js/show_list.js
  src/main/resources/templates/fragment/footer.html
  src/main/resources/templates/project/recruit_job.html
  src/main/resources/templates/project/show_list.html
Labels: bug

#180 Feat: 프로젝트모집->자랑 변환
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/dto/req/project/ShowUpdateDto.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/web/api/ApiProjectController.java
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/templates/member/myproject_list.html
  src/main/resources/templates/project/show_detail.html
Labels: enhancement

#182 Update README.md
  README.md
Labels: enhancement
