Repository PKNU-JavaStudy/mozip_backend, pull requests merged in 2024-06, with the labels that each got.

#8 [#7]Feat: 메인페이지 배너 및 파비콘,로고 추가
  src/main/resources/static/css/common.css
  src/main/resources/static/css/create.css
  src/main/resources/static/css/detail.css
  src/main/resources/static/css/index.css
  src/main/resources/static/css/list.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/css/user.css
  src/main/resources/static/img/banner01.jpg
  src/main/resources/static/img/banner02.jpg
  src/main/resources/static/img/favicon.ico
  src/main/resources/static/img/logo.png
  src/main/resources/static/img/logo1.png
  src/main/resources/static/img/logo2.png
  src/main/resources/static/js/index.js
  src/main/resources/templates/auth/find_id.html
  src/main/resources/templates/auth/find_password.html
  src/main/resources/templates/auth/join.html
  src/main/resources/templates/auth/login.html
  src/main/resources/templates/index.html
  src/main/resources/templates/member/mypage.html
  src/main/resources/templates/member/mypage_edit.html
  src/main/resources/templates/project/recruit_create.html
  src/main/resources/templates/project/recruit_detail.html
  src/main/resources/templates/project/recruit_list.html
  src/main/resources/templates/project/show_detail.html
  src/main/resources/templates/project/show_list.html
  src/main/resources/templates/team/teamnote.html
  src/main/resources/templates/team/teamnote_list.html
Labels: enhancement

#10 Feat: DB에서 데이터 들고오는 예제
  src/main/java/com/mozip/domain/member/Member.java
  src/main/java/com/mozip/domain/project/Project.java
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/dto/resp/ProjectListDto.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/web/ProjectController.java
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/mappers/TeamnoteMapper.xml
Labels: enhancement

#11 메인페이지 데이터 갖고오기 구현완료
  src/main/java/com/mozip/domain/member/MemberRepository.java
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/dto/resp/NewMemberListDto.java
  src/main/java/com/mozip/dto/resp/ProjectListDto.java
  src/main/java/com/mozip/service/MemberService.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/util/Util.java
  src/main/java/com/mozip/web/ProjectController.java
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/templates/index.html
Labels: enhancement

#14 Topic/recruit list
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/dto/resp/RecruitListDto.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/util/Util.java
  src/main/java/com/mozip/web/ProjectController.java
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/templates/project/recruit_list.html
Labels: enhancement

#15 Topic/join
  src/main/java/com/mozip/domain/member/JoinRepository.java
  src/main/java/com/mozip/dto/resp/JoinMemberDto.java
  src/main/java/com/mozip/service/AuthService.java
  src/main/java/com/mozip/web/AuthController.java
  src/main/resources/mappers/joinMapper.xml
  src/main/resources/static/js/join_effect.js
  src/main/resources/templates/auth/join.html
Labels: enhancement

#17 프로젝트 모집 상세 페이지 데이터 로딩
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/dto/resp/ProjectDetailDto.java
  src/main/java/com/mozip/dto/resp/ProjectMemberDto.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/web/ProjectController.java
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/static/img/mozip.png
  src/main/resources/static/sql/init.sql
  src/main/resources/templates/project/recruit_detail.html
Labels: enhancement

#22 Topic/teamnote list
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/domain/teamnote/TeamnoteRepository.java
  src/main/java/com/mozip/dto/resp/TeamnoteListDto.java
  src/main/java/com/mozip/service/TeamService.java
  src/main/java/com/mozip/web/TeamController.java
  src/main/resources/mappers/TeamnoteMapper.xml
  src/main/resources/static/sql/init.sql
  src/main/resources/templates/team/teamnote_list.html
Labels: enhancement

#23 Topic/show list
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/dto/resp/ShowListDto.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/web/ProjectController.java
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/templates/project/recruit_list.html
  src/main/resources/templates/project/show_list.html
Labels: enhancement

#25 [#24]Feat: 프로젝트 스킬 이미지 매핑
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/com/mozip/dto/resp/ShowListDto.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/web/ProjectController.java
  src/main/resources/.DS_Store
  src/main/resources/static/.DS_Store
  src/main/resources/static/img/Angular_icon.png
  src/main/resources/static/img/Cplus_icon.png
  src/main/resources/static/img/Csharp_icon.png
  src/main/resources/static/img/Flask_icon.png
  src/main/resources/static/img/Flutter_icon.png
  src/main/resources/static/img/NodeJs_icon.png
  src/main/resources/static/img/aws.svg
  src/main/resources/static/img/css_icon.png
  src/main/resources/static/img/docker.svg
  src/main/resources/static/img/flutter.svg
  src/main/resources/static/img/git_icon.png
  src/main/resources/static/img/github_icon.png
  src/main/resources/static/img/html_icon.png
  src/main/resources/static/img/java.svg
  src/main/resources/static/img/java_icon.png
  src/main/resources/static/img/javascript.svg
  src/main/resources/static/img/jest.svg
  src/main/resources/static/img/js_icon.png
  src/main/resources/static/img/kotlin.svg
  src/main/resources/static/img/logo1.png
  src/main/resources/static/img/mongodb.svg
  src/main/resources/static/img/mysql.svg
  src/main/resources/static/img/nodejs.svg
  src/main/resources/static/img/php.svg
  src/main/resources/static/img/php_icon.png
  src/main/resources/static/img/python.svg
  src/main/resources/static/img/python_icon.png
  src/main/resources/static/img/react.svg
  src/main/resources/static/img/react_icon.png
  src/main/resources/static/img/react_native_icon.png
  src/main/resources/static/img/reactnative.svg
  src/main/resources/static/img/spring.svg
  src/main/resources/static/img/spring_icon.png
  src/main/resources/static/img/svelte.svg
  src/main/resources/static/img/typeScript_icon.png
  src/main/resources/static/img/vueJs_icon.png
  src/main/resources/templates/project/recruit_list.html
  src/main/resources/templates/project/show_list.html
Labels: enhancement

#26 로그인 구현 및 추가작업
  build.gradle
  src/main/java/com/mozip/domain/member/AuthRepository.java
  src/main/java/com/mozip/domain/member/Member.java
  src/main/java/com/mozip/dto/req/LoginDto.java
  src/main/java/com/mozip/service/AuthService.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/util/SessionConst.java
  src/main/java/com/mozip/web/AuthController.java
  src/main/java/com/mozip/web/MemberController.java
  src/main/java/com/mozip/web/ProjectController.java
  src/main/java/com/mozip/web/TeamController.java
  src/main/resources/application-dev.yml
  src/main/resources/mappers/AuthMapper.xml
  src/main/resources/mappers/joinMapper.xml
  src/main/resources/static/img/mozip.png
  src/main/resources/templates/auth/login.html
  src/main/resources/templates/fragment/header.html
  src/main/resources/templates/project/recruit_list.html
Labels: enhancement

#29 Topic/page style
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/web/AuthController.java
  src/main/java/com/mozip/web/TeamController.java
  src/main/resources/static/css/common.css
  src/main/resources/static/css/detail.css
  src/main/resources/templates/fragment/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/project/recruit_detail.html
  src/main/resources/templates/project/show_list.html
Labels: enhancement

#31 마이페이지 DB 연결, 권한 설정
  src/main/java/com/mozip/domain/member/MemberRepository.java
  src/main/java/com/mozip/dto/resp/MyBookmarkListDto.java
  src/main/java/com/mozip/dto/resp/MyProjectDto.java
  src/main/java/com/mozip/dto/resp/MypageDto.java
  src/main/java/com/mozip/service/MemberService.java
  src/main/java/com/mozip/web/MemberController.java
  src/main/resources/mappers/AuthMapper.xml
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/templates/member/mypage.html
Labels: enhancement

#34 Topic/show detail
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/dto/resp/ShowDetailDto.java
  src/main/java/com/mozip/service/AuthService.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/web/ProjectController.java
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/templates/project/recruit_detail.html
  src/main/resources/templates/project/show_detail.html
  src/main/resources/templates/project/show_list.html
Labels: enhancement

#36 [#35]Feat: 모집 작성 페이지 수정
  src/main/resources/static/js/01jaeyoung.js
  src/main/resources/static/js/dynamicSkills.js
  src/main/resources/templates/project/recruit_create.html
Labels: bug

#37 Topic/subscribe email
  README.md
  build.gradle
  src/main/java/com/mozip/domain/member/AuthRepository.java
  src/main/java/com/mozip/service/EmailService.java
  src/main/java/com/mozip/web/ProjectController.java
  src/main/java/com/mozip/web/api/ApiEmailController.java
  src/main/resources/application-dev.yml
  src/main/resources/mappers/AuthMapper.xml
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/templates/project/recruit_detail.html
  src/main/resources/templates/project/show_list.html
Labels: enhancement

#42 Topic/recruit create
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/dto/req/ProjectCreateDto.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/util/Util.java
  src/main/java/com/mozip/web/ProjectController.java
  src/main/java/com/mozip/web/api/ApiProjectController.java
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/static/css/create.css
  src/main/resources/static/css/team_note.css
  src/main/resources/static/js/02donggun.js
  src/main/resources/static/js/dynamicSkills.js
  src/main/resources/templates/fragment/header.html
  src/main/resources/templates/project/recruit_create.html
  src/main/resources/templates/project/recruit_detail.html
  src/main/resources/templates/project/recruit_list.html
Labels: enhancement

#44 [#43]Feat: 조회수 카운트 기능 추가
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/web/ProjectController.java
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/templates/project/recruit_detail.html
  src/main/resources/templates/project/show_list.html
Labels: enhancement

#46 [#45]Fix: 프로젝트 상세페이지 수정
  src/main/java/com/mozip/web/ProjectController.java
Labels: bug

#47 Fix:Mapper(Repository)클래스 수정
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/web/ProjectController.java
Labels: bug

#49 [#48]Feat: 프로젝트 자랑 삭제 기능 추가 및 작성페이지 css 수정
  src/main/java/com/mozip/web/ProjectController.java
  src/main/resources/templates/project/show_detail.html
Labels: enhancement

#50 커밋오류 해결
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/dto/resp/ShowListDto.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/web/api/ApiProjectController.java
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/static/css/create.css
  src/main/resources/static/css/detail.css
  src/main/resources/templates/project/recruit_create.html
  src/main/resources/templates/project/recruit_detail.html
  src/main/resources/templates/project/show_detail.html
Labels: bug

#53 [#51]Feat: 좋아요 버튼 기능
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/dto/req/ProjectLikeDto.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/web/ProjectController.java
  src/main/java/com/mozip/web/api/ApiProjectController.java
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/static/css/detail.css
  src/main/resources/templates/project/show_detail.html
Labels: enhancement

#56 [#54]Rename: Likes파일 따로 분리하기
  src/main/java/com/mozip/domain/likes/Likes.java
  src/main/java/com/mozip/domain/likes/LikesRepository.java
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/service/LikesService.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/web/api/ApiProjectController.java
  src/main/resources/mappers/LikesMapper.xml
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/static/css/detail.css
  src/main/resources/templates/index.html
  src/main/resources/templates/project/show_detail.html
Labels: bug

#57 Topic/my page
  src/main/java/com/mozip/domain/member/AuthRepository.java
  src/main/java/com/mozip/domain/member/MemberRepository.java
  src/main/java/com/mozip/dto/req/JoinMemberDto.java
  src/main/java/com/mozip/dto/req/MypageEditDto.java
  src/main/java/com/mozip/dto/req/UpdateMypageEditDto.java
  src/main/java/com/mozip/service/AuthService.java
  src/main/java/com/mozip/service/MemberService.java
  src/main/java/com/mozip/web/AuthController.java
  src/main/java/com/mozip/web/MemberController.java
  src/main/java/com/mozip/web/api/ApiMemberController.java
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/static/css/mypage.css
  src/main/resources/templates/member/mypage.html
  src/main/resources/templates/member/mypage_edit.html
Labels: enhancement

#58 프로젝트모집 수정/삭제 기능 구현
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/dto/resp/ProjectEditDto.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/util/Util.java
  src/main/java/com/mozip/web/ProjectController.java
  src/main/java/com/mozip/web/api/ApiProjectController.java
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/static/css/detail.css
  src/main/resources/templates/project/recruit_create.html
  src/main/resources/templates/project/recruit_detail.html
  src/main/resources/templates/project/recruit_edit.html
  src/main/resources/templates/project/show_detail.html
Labels: bug, enhancement

#62 Topic/kakao login
  build.gradle
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/web/AuthController.java
  src/main/java/com/mozip/web/ProjectController.java
  src/main/java/com/mozip/web/api/ApiEmailController.java
  src/main/java/com/mozip/web/api/ApiProjectController.java
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/templates/auth/login.html
  src/main/resources/templates/fragment/header.html
  src/main/resources/templates/project/show_detail.html
  src/main/resources/templates/project/show_edit.html
Labels: enhancement

#63 [#59]Feat: 마이페이지 ui 수정
  src/main/resources/static/js/02donggun.js
  src/main/resources/templates/member/mypage_edit.html
Labels: bug

#65 프로젝트모집 상세페이지 프로젝트참여 구현
  build.gradle
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/web/api/ApiProjectController.java
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/templates/project/recruit_detail.html
Labels: enhancement

#68 Topic/show patch
  src/main/java/com/mozip/web/ProjectController.java
  src/main/resources/static/js/03yoonji.js
  src/main/resources/templates/fragment/header.html
  src/main/resources/templates/member/mypage_edit.html
  src/main/resources/templates/project/recruit_create.html
  src/main/resources/templates/project/show_edit.html
Labels: enhancement

#73 [#72]Feat: 멤버모집 검색 기능 구현
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/dto/resp/RecruitListDto.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/web/api/ApiProjectController.java
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/static/css/list.css
  src/main/resources/templates/project/recruit_list.html
Labels: enhancement

#71 사용자 프로필 이미지 구현
  .DS_Store
  src/main/java/com/mozip/config/WebConfig.java
  src/main/java/com/mozip/domain/member/MemberRepository.java
  src/main/java/com/mozip/dto/req/UpdateMypageEditDto.java
  src/main/java/com/mozip/dto/resp/NewMemberListDto.java
  src/main/java/com/mozip/dto/resp/ProjectMemberDto.java
  src/main/java/com/mozip/service/AuthService.java
  src/main/java/com/mozip/service/MemberService.java
  src/main/java/com/mozip/web/MemberController.java
  src/main/java/com/mozip/web/api/ApiEmailController.java
  src/main/java/com/mozip/web/api/ApiMemberController.java
  src/main/java/com/mozip/web/api/ApiProjectController.java
  src/main/resources/application-dev.yml
  src/main/resources/mappers/AuthMapper.xml
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/static/css/detail.css
  src/main/resources/static/css/index.css
  src/main/resources/static/css/mypage.css
  src/main/resources/static/js/02donggun.js
  src/main/resources/templates/fragment/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/member/mypage.html
  src/main/resources/templates/member/mypage_edit.html
  src/main/resources/templates/project/recruit_detail.html
  src/main/resources/templates/project/show_detail.html
Labels: enhancement

#79 북마크 수정
  src/main/java/com/mozip/domain/keep/Keep.java
  src/main/java/com/mozip/domain/keep/KeepRepository.java
  src/main/java/com/mozip/domain/likes/LikesRepository.java
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/dto/resp/ShowDetailDto.java
  src/main/java/com/mozip/service/KeepService.java
  src/main/java/com/mozip/service/LikesService.java
  src/main/java/com/mozip/web/ProjectController.java
  src/main/java/com/mozip/web/api/ApiProjectController.java
  src/main/resources/mappers/KeepMapper.xml
  src/main/resources/static/css/detail.css
  src/main/resources/templates/index.html
  src/main/resources/templates/member/mypage.html
  src/main/resources/templates/project/recruit_detail.html
  src/main/resources/templates/project/show_detail.html
Labels: bug

#80 마이페이지 오타 수정 커밋
  src/main/resources/templates/member/mypage.html
Labels: enhancement

#78 Topic/find
  src/main/java/com/mozip/domain/member/AuthRepository.java
  src/main/java/com/mozip/dto/req/FindEmailDto.java
  src/main/java/com/mozip/service/AuthService.java
  src/main/java/com/mozip/web/AuthController.java
  src/main/resources/mappers/AuthMapper.xml
  src/main/resources/templates/auth/find_id.html
Labels: enhancement

#81 마이페이지 정보 버그 해결 및 모집완료 버튼 버그 해결
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/templates/member/mypage.html
  src/main/resources/templates/project/recruit_detail.html
Labels: bug

#82 멤버추가 이메일 전송 기능 구현
  src/main/.DS_Store
  src/main/java/com/mozip/domain/member/AuthRepository.java
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/dto/resp/ProjectDetailDto.java
  src/main/java/com/mozip/service/EmailService.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/web/ProjectController.java
  src/main/java/com/mozip/web/api/ApiEmailController.java
  src/main/resources/mappers/AuthMapper.xml
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/templates/project/recruit_detail.html
Labels: enhancement

#84 Topic/recruit filter
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/web/api/ApiProjectController.java
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/templates/auth/login.html
  src/main/resources/templates/fragment/header.html
  src/main/resources/templates/project/recruit_list.html
Labels: enhancement

#85 Fix/total project
  src/main/resources/application-dev.yml
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/static/css/detail.css
  src/main/resources/static/css/list.css
Labels: bug

#92 Topic/search
  src/main/resources/application-dev.yml
  src/main/resources/static/css/create.css
  src/main/resources/static/css/detail.css
  src/main/resources/static/css/index.css
  src/main/resources/static/css/list.css
  src/main/resources/static/js/index.js
  src/main/resources/templates/index.html
  src/main/resources/templates/project/recruit_create.html
  src/main/resources/templates/project/recruit_detail.html
  src/main/resources/templates/project/recruit_list.html
  src/main/resources/templates/project/show_detail.html
Labels: bug, enhancement

#95 Fix/refactoring
  src/main/resources/mappers/AuthMapper.xml
  src/main/resources/static/img/mozip.png
  src/main/resources/static/img/profile_sample.png
  src/main/resources/templates/project/recruit_list.html
  src/main/resources/templates/project/show_detail.html
Labels: bug

#99 [#98]Feat: MySql 쿼리 변경 및 NCLOB 타입 삭제
  src/main/java/com/mozip/dto/req/MypageEditDto.java
  src/main/java/com/mozip/dto/req/UpdateMypageEditDto.java
  src/main/java/com/mozip/dto/resp/MypageDto.java
  src/main/java/com/mozip/dto/resp/NewMemberListDto.java
  src/main/java/com/mozip/dto/resp/ProjectDetailDto.java
  src/main/java/com/mozip/dto/resp/ProjectEditDto.java
  src/main/java/com/mozip/dto/resp/ProjectListDto.java
  src/main/java/com/mozip/dto/resp/RecruitListDto.java
  src/main/java/com/mozip/dto/resp/ShowDetailDto.java
  src/main/java/com/mozip/dto/resp/ShowEditDto.java
  src/main/java/com/mozip/dto/resp/TeamnoteListDto.java
  src/main/java/com/mozip/service/MemberService.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/service/TeamService.java
  src/main/java/com/mozip/web/api/ApiMemberController.java
  src/main/java/com/mozip/web/api/ApiProjectController.java
  src/main/resources/mappers/ProjectMapper.xml
Labels: enhancement

#101 백엔드 유효성 검사 및 AOP 처리
  build.gradle
  src/main/java/com/mozip/dto/req/FindEmailDto.java
  src/main/java/com/mozip/dto/req/JoinMemberDto.java
  src/main/java/com/mozip/dto/req/LoginDto.java
  src/main/java/com/mozip/dto/req/ProjectCreateDto.java
  src/main/java/com/mozip/dto/req/UpdateMypageEditDto.java
  src/main/java/com/mozip/dto/resp/ProjectEditDto.java
  src/main/java/com/mozip/dto/resp/ShowEditDto.java
  src/main/java/com/mozip/handler/aop/ValidationAdvice.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/web/AuthController.java
  src/main/java/com/mozip/web/MemberController.java
  src/main/java/com/mozip/web/api/ApiMemberController.java
  src/main/java/com/mozip/web/api/ApiProjectController.java
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/static/js/02donggun.js
  src/main/resources/static/sql/init.sql
  src/main/resources/templates/index.html
  src/main/resources/templates/project/recruit_create.html
  src/main/resources/templates/project/recruit_detail.html
  src/main/resources/templates/project/recruit_edit.html
  src/main/resources/templates/project/show_detail.html
  src/main/resources/templates/project/show_edit.html
Labels: enhancement

#103 [#102]스프링 시큐리티 추가
  README.md
  build.gradle
  src/main/java/com/mozip/config/SecurityConfig.java
  src/main/java/com/mozip/config/auth/PrincipalDetails.java
  src/main/java/com/mozip/config/auth/PrincipalDetailsService.java
  src/main/java/com/mozip/domain/member/AuthRepository.java
  src/main/java/com/mozip/domain/member/Member.java
  src/main/java/com/mozip/domain/member/Role.java
  src/main/java/com/mozip/dto/resp/ProjectEditDto.java
  src/main/java/com/mozip/service/AuthService.java
  src/main/java/com/mozip/web/AuthController.java
  src/main/java/com/mozip/web/MemberController.java
  src/main/java/com/mozip/web/ProjectController.java
  src/main/java/com/mozip/web/api/ApiEmailController.java
  src/main/java/com/mozip/web/api/ApiMemberController.java
  src/main/java/com/mozip/web/api/ApiProjectController.java
  src/main/resources/mappers/AuthMapper.xml
  src/main/resources/templates/auth/login.html
  src/main/resources/templates/fragment/header.html
  src/main/resources/templates/member/mypage.html
  src/main/resources/templates/project/recruit_create.html
  src/main/resources/templates/project/recruit_detail.html
  src/main/resources/templates/project/recruit_list.html
  src/main/resources/templates/project/show_detail.html
Labels: enhancement

#104 Fix/join
  .DS_Store
  src/main/java/com/mozip/service/AuthService.java
  src/main/java/com/mozip/web/AuthController.java
  src/main/resources/static/js/join_effect.js
  src/main/resources/templates/auth/join.html
Labels: bug

#105 카카오 로그인 구현
  src/main/java/com/mozip/config/SecurityConfig.java
  src/main/java/com/mozip/config/auth/PrincipalDetails.java
  src/main/java/com/mozip/config/auth/PrincipalOauth2UserService.java
  src/main/java/com/mozip/domain/member/Member.java
  src/main/java/com/mozip/dto/req/JoinMemberDto.java
  src/main/java/com/mozip/service/MemberService.java
  src/main/resources/application-dev.yml
  src/main/resources/templates/auth/login.html
Labels: enhancement

#108 Fix: 타임리프 경로 수정
  src/main/java/com/mozip/web/ProjectController.java
  src/main/java/com/mozip/web/TeamController.java
  src/main/resources/application-dev.yml
  src/main/resources/templates/project/recruit_list.html
  src/test/java/com/mozip/MozipApplicationTests.java
Labels: bug

#107 [#106] Feat: 어노테이션 추가
  src/main/java/com/mozip/dto/req/member/JoinMemberDto.java
Labels: enhancement

#113 셀렉트 창 옵션 추가
  src/main/resources/templates/member/mypage_edit.html
  src/main/resources/templates/project/recruit_create.html
  src/main/resources/templates/project/recruit_edit.html
  src/main/resources/templates/project/show_edit.html
  src/main/resources/templates/project/show_list.html
Labels: enhancement

#115 회원탈퇴 기능 구현
  src/main/java/com/mozip/config/SecurityConfig.java
  src/main/java/com/mozip/config/auth/PrincipalDetails.java
  src/main/java/com/mozip/config/auth/PrincipalOauth2UserService.java
  src/main/java/com/mozip/domain/member/MemberRepository.java
  src/main/java/com/mozip/service/AuthService.java
  src/main/java/com/mozip/service/MemberService.java
  src/main/java/com/mozip/web/AuthController.java
  src/main/java/com/mozip/web/api/ApiMemberController.java
  src/main/resources/mappers/MemberMapper.xml
  src/main/resources/templates/fragment/header.html
  src/main/resources/templates/project/recruit_detail.html
Labels: enhancement

#116 프로젝트모집 카테고리 필터 버그해결
  src/main/java/com/mozip/dto/req/member/FindPwDto.java
  src/main/java/com/mozip/dto/req/member/JoinMemberDto.java
  src/main/java/com/mozip/dto/req/member/LoginDto.java
  src/main/java/com/mozip/dto/req/member/UpdateMypageEditDto.java
  src/main/java/com/mozip/dto/req/project/FindEmailDto.java
  src/main/java/com/mozip/dto/req/project/ProjectCreateDto.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/resources/templates/project/recruit_edit.html
Labels: bug

#117 Feat: 무한스크롤 구현
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/java/com/mozip/web/ProjectController.java
  src/main/java/com/mozip/web/api/ApiProjectController.java
  src/main/resources/mappers/ProjectMapper.xml
  src/main/resources/templates/project/recruit_list.html
Labels: enhancement

#118 Feat: 프로젝트 기본 샘플이미지 세팅
  src/main/java/com/mozip/domain/project/ProjectRepository.java
  src/main/java/com/mozip/service/ProjectService.java
  src/main/resources/mappers/ProjectMapper.xml
Labels: bug

#119 마이페이지 사용자 정보 기본 값 변경 및 수정
  src/main/resources/mappers/AuthMapper.xml
  src/main/resources/static/css/mypage.css
  src/main/resources/templates/member/mypage.html
Labels: enhancement
